# Adapted from https://dev.to/ysfaran/how-to-use-playwright-with-github-actions-and-github-pages-4gdl
name: Delete Playwright Report for Branch

on:
  delete:

# ensures that currently running Playwright workflows are canceled if branch is deleted
concurrency:
  group: Playwright-${{ github.event.ref }}

jobs:
  delete_reports:
    name: Delete Playwright Reports
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'branch' }}
    env:
      # name of the branch that was just deleted
      BRANCH_NAME: ${{ github.event.ref }}
    steps:
#### use this section if you are adding branch protections to your gh-pages branch ####
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
#### end of branch protection settings ####
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Delete Data for Branch
        timeout-minutes: 3
        working-directory: _data/playwright-reports/branches/
        run: |
          # delete the data branch directory if it exists
          if [[ -d $BRANCH_NAME ]]; then
            rm -rf $BRANCH_NAME
            echo "Deleted Playwright Data for $BRANCH_NAME from GitHub Pages" >> "$GITHUB_STEP_SUMMARY"
          else 
            echo "Could not find Playwright Data for $BRANCH_NAME to delete"
          fi
      - name: Delete Reports for Branch
        timeout-minutes: 3
        working-directory: playwright-reports/branches/
        run: |
          # delete the report branch directory it it exists
          if [[ -d $BRANCH_NAME ]]; then
            rm -rf $BRANCH_NAME
            echo "Deleted Playwright Reports for $BRANCH_NAME from GitHub Pages" >> "$GITHUB_STEP_SUMMARY"
          else 
            echo "Could not find Playwright Reports for $BRANCH_NAME to delete"
          fi
      - name: Push Changes
        timeout-minutes: 3
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            # if there were no changes, do nothing
            echo "Did not have Playwright Data or Reports to delete" >> "$GITHUB_STEP_SUMMARY"
          else
            # if there were changes commit them and push them back to gh-pages
            # uncomment the next two lines if you are not using the branch protections from above
            # git config user.name "github-actions[bot]"
            # git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -am "workflow: remove all reports and data for branch $BRANCH_NAME"
            git pull origin gh-pages --rebase -s recursive -X ours
            git push
            echo "Deleted Playwright Data or Reports for $BRANCH_NAME from GitHub Pages" >> "$GITHUB_STEP_SUMMARY"
          fi
