name: Playwright Tests

on:
  push:
    branches: # specify branches you want to trigger on or ignore
      - "*"
      - "!gh-pages"

# ensures that currently running Playwright workflows are canceled if branch is deleted
concurrency:
  group: Playwright-${{ github.event.ref }}
  cancel-in-progress: true

# this action needs the same permissions as the Push to GitHub Pages action because it is calling it
permissions:
  contents: write
  actions: read

jobs:
  # add any set up jobs needed to get e2e tests running in GitHub Actions
  e2e:
    runs-on: ubuntu-latest
    env:
      JSON_ARTIFACT_ID: json-playwright-report
      HTML_ARTIFACT_ID: html-playwright-report
    outputs:
      # these outputs access outputs from the steps and will be used in the publish job
      json_artifact_id: ${{ env.JSON_ARTIFACT_ID }}
      json_deploy_to: _data/${{ steps.variables.outputs.report_path }}
      html_artifact_id: ${{ env.HTML_ARTIFACT_ID }}
      html_deploy_to: ${{ steps.variables.outputs.report_path }}
      commit_msg: ${{ steps.variables.outputs.commit_msg }}
      output_url: ${{ steps.variables.outputs.report_path }}${{ steps.variables.outputs.report_name }}.html
      actualResult: ${{ steps.e2e-test.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#### this is our set up for installing and running the tests, update this with your set up and test run ####
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run e2e Tests
        id: e2e-test
        continue-on-error: true
        run: pnpm exec playwright test
#### end set up and test run ####
      - name: Set Report Path and Name
        id: variables
        # create variables for renaming the reports and for where they need to be deployed to
        # if the branch is main, the reports should be named main and they should be stored under playwright-reports/
        # if the branch is a feature branch, the reports should be named after the run id and the should be stored under playwright-reports/branchs/[branch_name] 
        # the commit messages should also be specific to the type of branch
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            echo "report_path=playwright-reports/" >> "$GITHUB_OUTPUT"
            echo "report_name=main" >> "$GITHUB_OUTPUT"
            echo "commit_msg=update Playwright report for main" >> "$GITHUB_OUTPUT"
          else
            echo "report_path=playwright-reports/branches/${{ github.ref_name }}/" >> "$GITHUB_OUTPUT"
            echo "report_name=${{ github.run_id }}" >> "$GITHUB_OUTPUT"
            echo "commit_msg=add Playwright report for branch ${{ github.ref_name }}, run-id ${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Rename Reports
        # working-directory should point to the location of your Playwright reports
        working-directory: playwright-reports/
        # rename the reports to the report_name from above
        # change the names and locations to match your Playwright configurations
        run: |
          mv playwright-summary.json ${{ steps.variables.outputs.report_name }}.json
          cd html-report
          mv index.html ${{ steps.variables.outputs.report_name }}.html
      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        id: upload-json
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.JSON_ARTIFACT_ID }}
          # path should point to the location of your json Playwright report
          path: playwright-reports/${{ steps.variables.outputs.report_name }}.json
          retention-days: 30
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        id: upload-html
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.HTML_ARTIFACT_ID }}
          # path should point to the location of your html Playwright report
          path: playwright-reports/html-report/${{ steps.variables.outputs.report_name }}.html
          retention-days: 30

  publish:
    needs: [e2e]
    # call the push-to-gh-pages workflow to add the artifacts to gh-pages
    uses: ./.github/workflows/push-to-gh-pages.yml
    with:
      FILE_1_ARTIFACT_ID: ${{ needs.e2e.outputs.json_artifact_id }}
      FILE_1_DEPLOY_TO: ${{ needs.e2e.outputs.json_deploy_to }}
      FILE_2_ARTIFACT_ID: ${{ needs.e2e.outputs.html_artifact_id }}
      FILE_2_DEPLOY_TO: ${{ needs.e2e.outputs.html_deploy_to }}
      COMMIT_MSG: ${{ needs.e2e.outputs.commit_msg }}
      URL_PATH: ${{ needs.e2e.outputs.output_url }}
    secrets: inherit # allow called workflow to use GitHub secrets
