name: Publish All Release Notes

on:
  workflow_dispatch:

# this action needs the same permissions as the Push to GitHub Pages action because it is calling it
permissions:
  contents: write
  actions: read

jobs:
  get-all-tags:
    name: Get All Tags
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tag-names.outputs.tags }}
    steps:
      - name: Get Tags
        uses: octokit/request-action@v2.x
        id: get-tags
        with:
          route: /repos/${{ github.repository }}/tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Tag Names
        id: tag-names
        run: |
          TAGS=$(echo '${{ steps.get-tags.outputs.data }}' | jq '[.[].name] | tostring' )
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

  release-note:
    needs: get-all-tags
    strategy:
      matrix:
        tag: ${{ fromJson(needs.get-all-tags.outputs.tags) }}
    uses: ./.github/workflows/release-notes.yml
    with:
      TAG: ${{ matrix.tag }}
    secrets: inherit # allow called workflow to use GitHub secrets
