name: GitHub Pages Build and Deploy

on:
  # trigger this workflow when e2e tests complete or when branch reports were deleted
  workflow_run:
    workflows:
      - Playwright Tests
      - Delete Playwright Report for Branch
      - Code Coverage Report
    types:
      - completed
  # allow manually triggering workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Build Site
        run: |
          rm -rf .bundle
          rm -rf Gemfile.lock
          bundle install --no-deployment
          bundle exec jekyll build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
