name: GitHub Pages Build and Deploy

on:
  # rebuild and deploy on push to gh-pages
  push:
    branches:
      - gh-pages
  # allow manually triggering workflow
  workflow_dispatch:

# ensures that currently running GitHub Pages Build and Deploy workflow are canceled if another one starts
concurrency:
  group: publish-github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Build Site
        run: |
          rm -rf .bundle
          rm -rf Gemfile.lock
          bundle install --no-deployment
          bundle exec jekyll build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    if: ${{ github.event == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
