# Adapted from https://dev.to/ysfaran/how-to-use-playwright-with-github-actions-and-github-pages-4gdl
name: Push to GitHub Pages

on:
  workflow_call:
    # the inputs take in two artifacts that can be deployed
    # to different locations, only the first file is required
    inputs:
      FILE_1_ARTIFACT_ID:
        type: string
        required: true
      FILE_1_DEPLOY_TO:
        type: string
        required: true
      FILE_2_ARTIFACT_ID:
        type: string
        required: false
      FILE_2_DEPLOY_TO:
        type: string
        required: false
      COMMIT_MSG:
        type: string
        required: true
      URL_PATH:
        type: string
        required: true

permissions:
  contents: write
  actions: read

jobs:
  push-to-pages:
    runs-on: ubuntu-latest
    steps:
#### use this section if you are adding branch protections to your gh-pages branch ####
      - name: Get GitHub token
        id: github_token
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo GITHUB_TOKEN=$(gha-token --app-id ${{ vars.APP_ID }} --installation-id ${{ vars.INSTALLATION_ID }} --private-key "$PRIVATE_KEY") >> $GITHUB_OUTPUT
#### end of branch protection settings ####
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
#### use this section if you are adding branch protections to your gh-pages branch ####
          token: ${{ steps.github_token.outputs.GITHUB_TOKEN }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
#### end of branch protection settings ####
      - name: Download File 1
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.FILE_1_ARTIFACT_ID }}
          path: ${{ inputs.FILE_1_DEPLOY_TO }}
      - name: Download File 2
        uses: actions/download-artifact@v4
        if: inputs.FILE_2_ARTIFACT_ID && inputs.FILE_2_DEPLOY_TO
        with:
          name: ${{ inputs.FILE_2_ARTIFACT_ID }}
          path: ${{ inputs.FILE_2_DEPLOY_TO }}
      - name: Push to GitHub Pages Branch
        run: |
          git config --global user.name 'publish-playwright app'
          git config --global user.email 'publish-playwright-app@users.noreply.github.com'
          git add -A
          git commit -am "${{ inputs.COMMIT_MSG }}"
          git pull origin gh-pages --rebase -s recursive -X ours
          git push
          echo "New URL: https://fearlesssolutions.github.io/publish-playwright/${{ inputs.URL_PATH }}" >> "$GITHUB_STEP_SUMMARY"
