name: Publish Release Notes

on:
  workflow_call:
    inputs:
      TAG:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      TAG:
        type: string
        required: true

# this action needs the same permissions as the Push to GitHub Pages action because it is calling it
permissions:
  contents: write
  actions: read

jobs:
  generate-post:
    name: Generate Release Post
    runs-on: ubuntu-latest
    outputs:
      artifact_id: ${{ steps.filename.outputs.filename }}
    steps:
      - name: Get Release Info
        uses: octokit/request-action@v2.x
        id: get_release
        with:
          route: /repos/${{ github.repository }}/releases/tags/${{ inputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format Published At Date
        run: |
          published_at=$(echo ${{ steps.get_release.outputs.data.published_at }}| cut -d "T" -f 1)
          echo "PUB_DATE=$published_at" >> "$GITHUB_ENV"
      - name: Create Filename
        id: filename
        run: |
          # Normalize the tag name to replace the `.` with `-`
          tag_name=$(echo "${{ inputs.TAG }}" | sed "s/\./-/g")
          name="$PUB_DATE-$tag_name"
          echo "post_name=$name" >> "$GITHUB_OUTPUT"
          echo "filename=$name.md" >> "$GITHUB_OUTPUT"
      - name: Create Post
        run: |
          echo """---
          title: ${{ inputs.TAG }}
          tag: ${{ inputs.TAG }}
          category: release
          date: $PUB_DATE
          created_at: ${{ steps.get_release.outputs.data.created_at }}
          published_at: ${{ steps.get_release.outputs.data.published_at }}
          author: ${{ steps.get_release.outputs.data.author.login }}
          author_avatar: ${{ steps.get_release.outputs.data.author.avatar_url }}
          author_link: ${{ steps.get_release.outputs.data.author.html_url }}
          html_url: ${{ steps.get_release.outputs.data.html_url }}
          prerelease: ${{ steps.get_release.outputs.data.prerelease }}
          ---

          ${{ steps.get_release.outputs.data.body }}
          """ > ${{ steps.filename.outputs.filename }}
      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.filename.outputs.filename }}
          path: ${{ steps.filename.outputs.filename }}
          retention-days: 30

  publish:
    needs: [generate-post]
    uses: ./.github/workflows/push-to-gh-pages.yml
    with:
      FILE_1_ARTIFACT_ID: ${{ needs.generate-post.outputs.artifact_id }}
      FILE_1_DEPLOY_TO: _posts/releases/
      COMMIT_MSG: "adding release ${{ inputs.TAG }} to the release notes"
      URL_PATH: releases/
    secrets: inherit # allow called workflow to use GitHub secrets
