on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Refs ${{ github.event.ref }}"
          echo "Tags ${{ github.event.tag }}"
          echo "Tag Name ${{ github.event.release.tag_name }}"
          echo "Release Notes ${{ github.event.release.body }}"
