name: Release

on:
  release:
    types: [published]

# this action needs the same permissions as the Push to GitHub Pages action because it is calling it
permissions:
  contents: write
  actions: read

jobs:
  release-note:
    uses: ./.github/workflows/release-notes.yml
    with:
      TAG: ${{ github.event.release.tag_name }}
    secrets: inherit # allow called workflow to use GitHub secrets
