on:
  release:
    types: [published, unpublished, created, edited, prereleased, released]

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Type ${{ github.event.action }}"
          echo "Tag Name ${{ github.event.release.tag_name }}"
          echo "Release Notes ${{ github.event.release.body }}"
