on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.refs }}"
          echo "${{ github.event.tags }}"
